"""Création des tables Admin, Employe, Pointage, Absence

Revision ID: 9da8a0d425f5
Revises: 
Create Date: 2026-08-23 01:45:30.776539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da8a0d425f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('heure_arrivee_prevue', sa.Time(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('poste', sa.String(length=100), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('date_absence', sa.Date(), nullable=False),
    sa.Column('motif', sa.String(length=255), nullable=True),
    sa.Column('date_declaration', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pointages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employe_id', sa.Integer(), nullable=False),
    sa.Column('date_pointage', sa.Date(), nullable=False),
    sa.Column('heure_arrivee', sa.Time(), nullable=True),
    sa.Column('heure_depart', sa.Time(), nullable=True),
    sa.Column('en_retard', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employe_id', 'date_pointage', name='uq_employe_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pointages')
    op.drop_table('absences')
    op.drop_table('employes')
    op.drop_table('admins')
    # ### end Alembic commands ###
