"""Simplification du modele Admin - suppression du champ nom

Revision ID: d36da436e705
Revises: 9da8a0d425f5
Create Date: 2026-08-23 02:08:41.566653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd36da436e705'
down_revision = '9da8a0d425f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('nom')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
